twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        locales: '%app.locales%'
        email: '%app.email%'
        phone: '%app.phone%'
        address: '%app.address%'
        linkedin: '%app.linkedin%'
        googleMap: '%app.google_map%'
        frontendManager: '@App\Utils\Features\Frontend\DataManager'

when@test:
    twig:
        strict_variables: true
