version: "3.7"

services:
  app:
    image: sf_mgorski.dev
    build:
      context: ./..
    ports:
      - ${APP_EXPOSED_PORT}:82
    volumes:
      - ./../:/var/www/html
      - ./app/config/vhosts:/etc/apache2/sites-enabled
      - ./app/config/dir/dir.conf:/etc/apache2/mods-enabled/dir.conf
    networks:
      - nginx
  database:
    image: postgres:15.1
    ports:
      - ${DATABASE_EXPOSED_PORT}:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - nginx
  node:
    image: node:22-slim
    volumes:
      - ./../:/var/www/html
    command: sh -c "cd /var/www/html && rm -f package-lock.json && rm -rf node_modules && npm install --force && npx encore dev"
    networks:
      - nginx

networks:
  nginx:
    external: true
    driver: bridge

volumes:
  postgres:
    driver: local
