version: "3.7"

services:
  app:
    image: sf_cms
    build:
      context: ./..
      dockerfile: ./docker/app/Dockerfile
    ports:
      - ${APP_EXPOSED_PORT}:82
    volumes:
      - ./../:/var/www/html
      - ./app/config/vhosts:/etc/apache2/sites-enabled
      - ./app/config/dir/dir.conf:/etc/apache2/mods-enabled/dir.conf
  database:
    image: postgres:15.1
    ports:
      - ${DATABASE_EXPOSED_PORT}:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  node:
    image: node:22-slim
    volumes:
      - ./../:/var/www/html
    command: sh -c "cd /var/www/html && rm -f package-lock.json && rm -rf node_modules && npm install && npx encore dev --watch"
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - ${MAILHOG_EXPOSED_PORT}:8025

volumes:
  postgres:
    driver: local
