version: "3.7"

services:
  sf_cms_app:
    container_name: sf_cms_app
    image: sf_cms
    build:
      context: ./..
      dockerfile: ./docker/app/Dockerfile
    ports:
      - ${CMS_APP_EXPOSED_PORT}:82
    volumes:
      - ./../:/var/www/html
      - ./app/config/vhosts:/etc/apache2/sites-enabled
      - ./app/config/dir/dir.conf:/etc/apache2/mods-enabled/dir.conf
    networks:
      - sf_cms
  sf_cms_database:
    container_name: sf_cms_database
    image: postgres:15.1
    ports:
      - ${CMS_DATABASE_EXPOSED_PORT}:5432
    volumes:
      - postgres_sf_cms:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${CMS_DATABASE_NAME}
      POSTGRES_USER: ${CMS_DATABASE_USER}
      POSTGRES_PASSWORD: ${CMS_DATABASE_PASSWORD}
    networks:
      - sf_cms
  sf_cms_node:
    container_name: sf_cms_node
    image: node:22-slim
    volumes:
      - ./../:/var/www/html
    command: sh -c "cd /var/www/html && rm -f package-lock.json && rm -rf node_modules && npm install --force && npx encore dev"
    networks:
      - sf_cms

networks:
  sf_cms:
    external: true
    driver: bridge

volumes:
  postgres_sf_cms:
    driver: local
