monolog:
    handlers:
        main:
            action_level: error
            handler: nested
            buffer_size: 50
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
        nested:
            type: stream
            path: php://stderr
            level: debug
            formatter: monolog.formatter.json
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
