parameters:
    locale: 'pl'
    app.locales: pl|en
    app.email: '%env(APP_EMAIL)%'
    app.phone: '%env(APP_PHONE)%'
    app.address: '%env(APP_ADDRESS)%'
    app.linkedin: '%env(APP_LINKEDIN)%'
    app.google_map: '%env(APP_GOOGLE_MAP)%'
    encryption_manager.method: '%env(ENCRYPTION_MANAGER_METHOD)%'
    encryption_manager.iv: '%env(ENCRYPTION_MANAGER_IV)%'
    ovh.application_key: '%env(OVH_APPLICATION_KEY)%'
    ovh.application_secret: '%env(OVH_APPLICATION_SECRET)%'
    ovh.api_endpoint: '%env(OVH_API_ENDPOINT)%'
    ovh.consumer_key: '%env(OVH_CONSUMER_KEY)%'
    dropbox.key: '%env(DROPBOX_API_KEY)%'
    dropbox.secret: '%env(DROPBOX_API_SECRET)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $projectDir: '%kernel.project_dir%'
            $seleniumUrl: '%env(SELENIUM_URL)%'
            $camasutraServices: !tagged_iterator 'app.camasutra'
            $integrationsServices: !tagged_iterator 'app.integration'
    _instanceof:
        App\Tools\Crawler\Camasutra\CamasutraInterface:
            tags: [name: 'app.camasutra']
        App\Tools\Integration\IntegrationInterface:
            tags: [ name: 'app.integration' ]

    App\:
        resource: '../src/'
        exclude:
            - '../src/{DependencyInjection,Entity,Message,Tests,Kernel.php}'
            - '../src/**/Model'

    entity.listener:
        class: App\EventListener\EntityListener
        arguments:
            - '@App\Security\EncryptionManager'
        tags:
            - { name: doctrine.event_listener, event: postLoad }

    App\Tools\Mailer\MailerWrongTypeException:
        autowire: false

    App\Tools\String\StringConverter:
        autowire: false

    App\Tools\Mailer\AbstractMailCreator:
        autowire: false

    App\Tools\Image\Image:
        autowire: false

    Ovh\Api:
        autowire: true
        arguments: [
            '%ovh.application_key%',
            '%ovh.application_secret%',
            '%ovh.api_endpoint%',
            '%ovh.consumer_key%'
        ]

    Spatie\Dropbox\Client:
        factory: [App\Factory\DropboxClient, create]

    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
