parameters:
  locale: 'en'
  app.locales: pl|en
  app.email: '%env(APP_EMAIL)%'
  app.address: '%env(APP_ADDRESS)%'
  app.github: '%env(APP_GITHUB)%'
  app.linkedin: '%env(APP_LINKEDIN)%'
  app.google_map: '%env(APP_GOOGLE_MAP)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $appPhoneNumber: '%env(APP_PHONE_NUMBER)%'
      $appEmail: '%env(APP_EMAIL)%'
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
