parameters:
    locale: 'pl'
    app.locales: pl|en
    app.email: '%env(APP_EMAIL)%'
    app.phone: '%env(APP_PHONE)%'
    app.address: '%env(APP_ADDRESS)%'
    app.linkedin: '%env(APP_LINKEDIN)%'
    app.google_map: '%env(APP_GOOGLE_MAP)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $seleniumUrl: '%env(SELENIUM_URL)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
