parameters:
    locale: 'pl'
    app.locales: pl|en
    app.email: '%env(APP_EMAIL)%'
    app.phone: '%env(APP_PHONE)%'
    app.address: '%env(APP_ADDRESS)%'
    app.linkedin: '%env(APP_LINKEDIN)%'
    app.google_map: '%env(APP_GOOGLE_MAP)%'
    encryption_manager.method: '%env(ENCRYPTION_MANAGER_METHOD)%'
    encryption_manager.iv: '%env(ENCRYPTION_MANAGER_IV)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $seleniumUrl: '%env(SELENIUM_URL)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/{DependencyInjection,Entity,Message,Tests,Kernel.php}'

    entity.listener:
        class: App\EventListener\EntityListener
        arguments:
            - '@App\Utils\Encryption\EncryptionManager'
        tags:
            - { name: doctrine.event_listener, event: postLoad }